# Generated by Django 4.0.4 on 2022-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_userc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='user',
        ),
        migrations.AddField(
            model_name='camera',
            name='user',
            field=models.ManyToManyField(to='main.userc', verbose_name='Users'),
        ),
    ]
